language: c
os: linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config gfortran netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev

before_script:
  - git clone https://github.com/NOAA-GFDL/FMS.git
  - cd FMS
  - autoreconf -i
  - ./configure CC=mpicc CPPFLAGS="-I/usr/include -Duse_LARGEFILE" FC=mpif90 FCFLAGs="-I/usr/include -Duse_LARGEFILE" LDFLAGS="-L/usr/lib" --prefix=$PWD/../local
  - make
  - make install
  - cd -

script:
  - autoreconf -i
  - ./configure FC=mpif90 FCFLAGS="-Ilocal/include"
  - make
