# Workflow for continuous integration tests
name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-8, gfortran-9]
    env:
      F90: ${{ matrix.fortran-compiler }}
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    # Set up Python and dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r urllib3 netcdf4 xarray dask scipy
    # Install FORTRAN compiler and NetCDF libraries
    - name: Install FORTRAN compiler
      run: sudo apt-get install ${{ matrix.fortran-compiler }} libnetcdf-dev
    # NetCDF FORTRAN library
    - name: NetCDF FORTRAN library
      run: |
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
        cd netcdf-fortran
        ./configure --prefix=/usr
        make
        sudo make install
    - name: Envionment
      run: |
        export RRTMGP_ROOT=$PWD
        export FC=${{ matrix.fortran-compiler }}
    - name: Stage RFMIP files
      run: |
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./stage_files.py
    - name: Make library, examples, tests
      run: |
      cd ${RRTMGP_ROOT}/build
      make clean
      make -j 2
      cd ${RRTMGP_ROOT}/tests
      make -C tests clean
      make clean
      make -j 1
      cd ${RRTMGP_ROOT}/examples/all-sky
      make clean
      make -j 2
      cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
      make clean
      make -j 2
    - name: Run examples, tests
      run: |
      cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
      python ./run-rfmip-examples.py --block_size 1800
      cd  ${RRTMGP_ROOT}/examples/all-sky
      python ./run-allsky-example.py
      cd  ${RRTMGP_ROOT}/tests
      cp ${RRTMGP_ROOT}/examples/rfmip-clear-sky/multiple_input4MIPs_radiation_RFMIP_UColorado-RFMIP-1-2_none.nc test_atmospheres.nc
      ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc
      ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc
    - name: Comparison
      run: |
      cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
      python ./compare-to-reference.py --fail=7.e-4
      cd ${RRTMGP_ROOT}/examples/all-sky
      python ./compare-to-reference.py
      cd ${RRTMGP_ROOT}/tests
      python verification.py
